### ISSUE TITLE
does not handle html comments

### ISSUE THREAD

**Issue by colmsjo** [millermedeiros/esformatter#419]
This simple file:
```
<html>
  <!-- A comment-->
</html>
```

Gives this error:

```
esformatter t.html 
Error: t.html:2:3 Unexpected token
SyntaxError: Unexpected token (2:3)
    at Parser.pp.raise (/Users/jonas/git/borealis/eslb/node_modules/babylon/index.js:1378:13)
    at Parser.pp.unexpected (/Users/jonas/git/borealis/eslb/node_modules/babylon/index.js:2817:8)
    at Parser.pp.jsxParseIdentifier (/Users/jonas/git/borealis/eslb/node_modules/babylon/index.js:4115:10)
    at Parser.pp.jsxParseNamespacedName (/Users/jonas/git/borealis/eslb/node_modules/babylon/index.js:4126:19)
    at Parser.pp.jsxParseElementName (/Users/jonas/git/borealis/eslb/node_modules/babylon/index.js:4141:19)
    at Parser.pp.jsxParseOpeningElementAt (/Users/jonas/git/borealis/eslb/node_modules/babylon/index.js:4218:20)
    at Parser.pp.jsxParseElementAt (/Users/jonas/git/borealis/eslb/node_modules/babylon/index.js:4242:29)
    at Parser.pp.jsxParseElementAt (/Users/jonas/git/borealis/eslb/node_modules/babylon/index.js:4255:30)
    at Parser.pp.jsxParseElement (/Users/jonas/git/borealis/eslb/node_modules/babylon/index.js:4291:15)
    at Parser.parseExprAtom (/Users/jonas/git/borealis/eslb/node_modules/babylon/index.js:4303:21)
```

Are there some settings I should use?

**Comment by millermedeiros** [comment]
this project only handles valid **JavaScript** files, it is not meant to format HTML files. We use [Babylon](https://github.com/babel/babel/tree/master/packages/babylon) internally to parse the JS, that's why you see it on the stack trace.
