### ISSUE TITLE
ES6: let/const export returns error.

### ISSUE THREAD

**Issue by v4n** [millermedeiros/esformatter#450]
When saving a file that contains `export let test = {};` esformatter returns:

```
stdin TypeError: Cannot read property 'indexOf' of undefined
    at exports._transformNode (/Users/V4N/.npm-packages/lib/node_modules/jsfmt/node_modules/esformatter-var-each/lib/esformatter-var-each.js:200:63)
    at Array.forEach (native)
    at Object.moonwalk (/Users/V4N/.npm-packages/lib/node_modules/jsfmt/node_modules/esformatter-var-each/node_modules/rocambole/rocambole.js:414:11)
    at Object.exports.transform (/Users/V4N/.npm-packages/lib/node_modules/jsfmt/node_modules/esformatter-var-each/lib/esformatter-var-each.js:311:13)
    at /Users/V4N/.npm-packages/lib/node_modules/jsfmt/node_modules/esformatter/lib/plugins.js:83:26
    at Array.forEach (native)
    at Object.exec (/Users/V4N/.npm-packages/lib/node_modules/jsfmt/node_modules/esformatter/lib/plugins.js:81:12)
    at Object.transform (/Users/V4N/.npm-packages/lib/node_modules/jsfmt/node_modules/mout/function/partial.js:23:22)
    at transform (/Users/V4N/.npm-packages/lib/node_modules/jsfmt/node_modules/esformatter/lib/transform.js:52:11)
    at doFormat (/Users/V4N/.npm-packages/lib/node_modules/jsfmt/node_modules/esformatter/lib/format.js:64:3)
```

JSFMT is using version 0.9.5 of esformatter.

**Comment by millermedeiros** [comment]
closing it since problem seems to be on the `esformatter-var-each` plugin: https://github.com/twolfson/esformatter-var-each/issues/6
